# -*- coding: utf-8 -*-
"""LCG_randgen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YVe6U4touuOT3GYhi-vYZP_yk5ExTtEH

# 1. Write your own LCG random generator with the following set of parameters a = 1103515245, c = 12345, m = 32768. 
Use it to solve the problems below. Remember to store your LCG code in a library file and it must not appear explicitly in the codes you write for the following problems.*
"""

a = 1103515245
c = 12345
m = 32768.
def myrand(x):  # LCG
	return ((a * x + c) % m) / m